# -*- mode: python; -*-

licenses(['notice'])  # Apache 2.0

#-----------------------------------------------------------------------------
# LIBRARIES

cc_library(name =  "nn_runtime",
           srcs = [
                    "neural_net.cpp",
                    "neuron.cpp",
                    "sigmoid_table.cpp",
                    "input_file_buffer.cpp"
                  ],
          deps = [ "//third_party/stl"] )

